### PR TITLE
Completed project

### PR DESCRIPTION
**Pull request by Kyle-Law**
Completed Project. Added README and cleared all HTML & CSS bugs
You may find the live link from README.md
Please review :)

### CODE REVIEW

**Comment by pelzolga123** [comment]
### Hi Kyle!
### I am marking this pull request as invalid due to following reasons:
* This project should have a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* Pull Request should have meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### Please kindly fix the above issues and send this pull request for review again.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by Kyle-Law** [comment]
Thank you @pelzolga123 for reviewing my code! Your suggestions have been implemented :)

**Review by mosesogwo — APPROVED** [review]
### :trophy:Great job @Kyle-Law .

Your project is great and is approved.

You may now merge to master and submit a project completion form.

**Optional: You may modify the background-gradient of the nav bar to look more like the original and reduce the font-size of the main section to match the original** 

**Happy Coding.**

### Status: Approved!

**Comment by Kyle-Law** [comment]
@mosesogwo Thank you!

**Pull request merged**
